simplified fadd code style

diff --git a/fadd b/fadd
--- a/fadd
+++ b/fadd
@@ -1,5 +1,6 @@
 #!/bin/bash
-# fadd takes two positive fixed point arguments of the form whole.fract
+# fadd takes two positive fixed point arguments 
+# each of the form whole.fract
 # and returns a fixed point number addition result 
 # for example: fadd 9.876543 0.987 10.863543
 
@@ -9,10 +10,14 @@ MAXINT=9223372036854775807 # 2**63-1
 # arguments verification
 NUM1=${1:?$PROGN needs fnum first argument}
 NUM2=${2:?$PROGN needs fnum second argument}
-if ! [[ $NUM1 =~ ^[+-]?[0-9]+[.][0-9]+$ ]]; then 
-	printf "$PROGN error: first argument $NUM1 is not an fnum\n"; exit 2; fi
-if ! [[ $NUM2 =~ ^[+-]?[0-9]+[.][0-9]+$ ]]; then 
-	printf "$PROGN error: second argument $NUM2 is not an fnum\n"; exit 2; fi
+[[ $NUM1 =~ ^[+-]?[0-9]+[.][0-9]+$ ]] || { 
+	printf "$PROGN error: first argument $NUM1 is not an fnum\n";
+    exit 2
+}
+[[ $NUM2 =~ ^[+-]?[0-9]+[.][0-9]+$ ]] || { 
+	printf "$PROGN error: second argument $NUM2 is not an fnum\n";
+    exit 2
+}
 
 # parse both args into whole and fractional parts	
 ARR1=(${NUM1//./ })
@@ -21,13 +26,14 @@ F1=${ARR1[1]}
 F2=${ARR2[1]}
 
 # swap fract parts so that $F1 is the longer
-if [[ ${#F1} -lt ${#F2} ]]; then 
-    FT=$F1; F1=$F2; F2=$FT; fi 
+[[ ${#F1} -lt ${#F2} ]] && { 
+    FT=$F1; F1=$F2; F2=$FT
+} 
 LF2=${#F2} #  save the shorter length
 
 # strip trailing zeroes from the longer F1 while longer
 while [[ ${#F1} -gt $LF2 ]]; do
- if [[ ${F1: -1:1} == 0 ]]; then F1=${F1:0:-1}; else break; fi
+[[ ${F1: -1:1} == 0 ]] && F1=${F1:0:-1} || break
 done
 LF1=${#F1} # finished chopping F1 now
 
@@ -39,9 +45,8 @@ WHOLE=$(( ${ARR1[0]}+${ARR2[0]} ))
 FRACT=$(( $F1+$F2 ))
 
 # check for fractional overflow i.e. >= 1
-if [[ ${#FRACT} -gt $LF1 ]]; then
+[[ ${#FRACT} -gt $LF1 ]] && {
     let WHOLE+=${FRACT:0:1}
     FRACT=${FRACT:1}
-fi
-expr $WHOLE.$FRACT
-
+}
+expr $WHOLE.$FRACT 
